// Replace these sample entries with your own reading history.
// Dates use YYYY-MM-DD for reliable sorting. year is finished year (or shelf year for unread books).
// Covers are loaded from Open Library; a local title/author fallback appears if unavailable.
const readingGoal = { year: 2026, target: 30 };
const books = [
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J. K. Rowling",
    isbn: "9781408894620",
    rating: 5,
    status: "read",
    genre: "Fantasy",
    year: 2026,
    finishedDate: "2026-09-18",
    review: "A magical and imaginative start to the Harry Potter series. The world-building is charming, the characters are memorable, and it was an enjoyable read from beginning to end.",
    tags: ["Fantasy", "Magic", "Adventure"]
  },
  {
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    author: 'Gabrielle Zevin',
    isbn: '9780593321201',
    rating: 5,
    status: 'read',
    genre: 'Fiction',
    year: 2026,
    finishedDate: '2026-08-25',
    review: 'I came for the games and stayed for the complicated friendship. A moving story about the things we build together.',
    tags: ['Friendship', 'Games', 'Creativity']
  },
  {
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    isbn: '9780857197689',
    rating: 4,
    status: 'read',
    genre: 'Finance',
    year: 2026,
    finishedDate: '2026-08-09',
    review: 'The most useful parts are about temperament rather than spreadsheets. A reminder that enough is a personal definition.',
    tags: ['Money', 'Psychology']
  },
  {
    title: 'The Midnight Library',
    author: 'Matt Haig',
    isbn: '9780525559474',
    rating: 4,
    status: 'read',
    genre: 'Fiction',
    year: 2026,
    finishedDate: '2026-07-20',
    review: 'A gentle, imaginative look at the lives we might have lived. Some lessons are quite direct, but the warmth stayed with me.',
    tags: ['Possibility', 'Life']
  },
  {
    title: 'Deep Work',
    author: 'Cal Newport',
    isbn: '9781455586691',
    rating: 4,
    status: 'read',
    genre: 'Self Development',
    year: 2026,
    finishedDate: '2026-07-05',
    review: 'A useful nudge to protect uninterrupted time. I tried shorter focus blocks instead of copying the more ambitious routines.',
    tags: ['Focus', 'Productivity']
  },
  {
    title: 'Everything I Know About Love',
    author: 'Dolly Alderton',
    isbn: '9780062968794',
    rating: 4,
    status: 'read',
    genre: 'Memoir',
    year: 2026,
    finishedDate: '2026-06-21',
    review: 'Funny, tender, and especially good on friendship. The everyday details made this feel like a long conversation.',
    tags: ['Friendship', 'Growing Up']
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    isbn: '9780735211292',
    rating: 5,
    status: 'read',
    genre: 'Self Development',
    year: 2026,
    finishedDate: '2026-03-15',
    review: 'A practical book about how small habits compound over time. Making the good choice easier felt more useful than waiting for motivation.',
    quote: 'You do not rise to the level of your goals.',
    tags: ['Habits', 'Productivity', 'Psychology']
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    isbn: '9780061122415',
    rating: 3,
    status: 'read',
    genre: 'Fiction',
    year: 2026,
    finishedDate: '2026-03-03',
    review: 'A simple fable with an appealing sense of wonder. I liked the journey more than the certainty of its message.',
    tags: ['Journey', 'Purpose']
  },
  {
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    isbn: '9780062316097',
    rating: 4,
    status: 'read',
    genre: 'History',
    year: 2026,
    finishedDate: '2026-02-22',
    review: 'Big questions and sweeping connections. Best read as a starting point for curiosity rather than the final word.',
    tags: ['History', 'Humanity']
  },
  {
    title: 'Normal People',
    author: 'Sally Rooney',
    isbn: '9781984822178',
    rating: 4,
    status: 'read',
    genre: 'Fiction',
    year: 2026,
    finishedDate: '2026-02-02',
    review: 'Small misunderstandings carry enormous weight here. I admired how much the quiet conversations managed to say.',
    tags: ['Relationships', 'Literary Fiction']
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    isbn: '9780399590504',
    rating: 5,
    status: 'read',
    genre: 'Memoir',
    year: 2026,
    finishedDate: '2026-01-19',
    review: 'An absorbing story of learning and finding a voice. The complicated feelings around family made it especially memorable.',
    tags: ['Education', 'Identity']
  },
  {
    title: 'Four Thousand Weeks',
    author: 'Oliver Burkeman',
    isbn: '9780374159122',
    rating: 5,
    status: 'read',
    genre: 'Self Development',
    year: 2026,
    finishedDate: '2026-01-06',
    review: 'A welcome invitation to stop treating life as an inbox. I finished it wanting to choose fewer things and enjoy them more.',
    tags: ['Time', 'Philosophy']
  },
  {
    title: 'The Book Thief',
    author: 'Markus Zusak',
    isbn: '9780375842207',
    rating: 5,
    status: 'read',
    genre: 'Fiction',
    year: 2025,
    finishedDate: '2025-12-12',
    review: 'The unusual narrator took a little getting used to, then completely won me over. A story about the shelter words can offer.',
    tags: ['Historical Fiction', 'Books']
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    isbn: '9780374533557',
    rating: 4,
    status: 'read',
    genre: 'Psychology',
    year: 2025,
    finishedDate: '2025-09-14',
    review: 'Dense enough that I read it slowly. The questions it raises about confidence and judgment are worth sitting with.',
    tags: ['Decisions', 'Thinking']
  },
  {
    title: 'Piranesi',
    author: 'Susanna Clarke',
    isbn: '9781635575637',
    rating: 5,
    status: 'read',
    genre: 'Fantasy',
    year: 2025,
    finishedDate: '2025-05-09',
    review: 'A strange and beautiful place to get lost. Going in knowing very little made the discoveries even better.',
    tags: ['Wonder', 'Mystery']
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    isbn: '9780441172719',
    rating: 4,
    status: 'read',
    genre: 'Science Fiction',
    year: 2024,
    finishedDate: '2024-11-16',
    review: 'The ecology and politics were as compelling as the adventure. A world that feels far bigger than a single story.',
    tags: ['Ecology', 'Worldbuilding']
  },
  {
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupéry',
    isbn: '9780156012195',
    rating: 5,
    status: 'read',
    genre: 'Fiction',
    year: 2024,
    finishedDate: '2024-04-07',
    review: 'Short enough for an afternoon, generous enough for a reread. Its tenderness feels different at different ages.',
    tags: ['Wonder', 'Classics']
  },
  {
    title: 'The Hobbit',
    author: 'J. R. R. Tolkien',
    isbn: '9780547928227',
    rating: 5,
    status: 'read',
    genre: 'Fantasy',
    year: 2023,
    finishedDate: '2023-10-10',
    review: 'An adventure with a wonderfully cozy heart. Bilbo remains very good company for a rainy weekend.',
    tags: ['Adventure', 'Classics']
  },
  {
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    isbn: '9780465050659',
    rating: null,
    status: 'reading',
    genre: 'Design',
    year: 2026,
    finishedDate: null,
    review: 'Currently noticing doors, switches, and confusing interfaces everywhere. Notes to follow when I finish.',
    tags: ['Design', 'Usability']
  },
  {
    title: 'Braiding Sweetgrass',
    author: 'Robin Wall Kimmerer',
    isbn: '9781571313560',
    rating: null,
    status: 'reading',
    genre: 'Nature',
    year: 2026,
    finishedDate: null,
    review: 'Reading a chapter at a time and letting it settle. I am enjoying the attention to reciprocity and place.',
    tags: ['Nature', 'Essays']
  },
  {
    title: 'A Gentleman in Moscow',
    author: 'Amor Towles',
    isbn: '9780143110439',
    rating: null,
    status: 'reading',
    genre: 'Fiction',
    year: 2026,
    finishedDate: null,
    review: 'Taking my time with the hotel and its inhabitants. Full thoughts once I reach the last page.',
    tags: ['Historical Fiction']
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    isbn: '9780593135204',
    rating: null,
    status: 'want-to-read',
    genre: 'Science Fiction',
    year: 2026,
    finishedDate: null,
    review: 'On my list for a weekend when I want a big scientific puzzle and an adventure.',
    tags: ['Space', 'Science']
  },
  {
    title: 'Still Life',
    author: 'Louise Penny',
    isbn: '9780312541538',
    rating: null,
    status: 'want-to-read',
    genre: 'Mystery',
    year: 2026,
    finishedDate: null,
    review: 'A village mystery for a slower reading week. No review yet.',
    tags: ['Mystery', 'On My List']
  },
  {
    title: 'On Writing',
    author: 'Stephen King',
    isbn: '9781439156810',
    rating: null,
    status: 'want-to-read',
    genre: 'Creativity',
    year: 2026,
    finishedDate: null,
    review: 'Saved for the mix of memoir and practical thoughts on the writing life.',
    tags: ['Writing', 'Craft']
  }
].map(book => ({
  ...book,
  cover: book.cover || `https://covers.openlibrary.org/b/isbn/${book.isbn}-L.jpg?default=false`
}));
