// Replace these sample entries with your own reading history.
// Dates use YYYY-MM-DD for reliable sorting. year is finished year (or shelf year for unread books).
// Covers are loaded from Open Library; a local title/author fallback appears if unavailable.
const readingGoal = { year: 2026, target: 30 };
const books = [
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J. K. Rowling",
    isbn: "9781408894620",
    rating: 4.47,
    status: "read",
    genre: "Fantasy",
    year: 2026,
    finishedDate: "2026-09-18",
    review: "A magical and imaginative start to the Harry Potter series. The world-building is charming, the characters are memorable, and it was an enjoyable read from beginning to end.",
    tags: ["Fantasy", "Magic", "Adventure"]
  },
  {
    title: "Harry Potter and the Chamber of Secrets",
    author: "J. K. Rowling",
    isbn: "9781338878936",
    rating: 4.43,
    status: "read",
    genre: "Fantasy",
    year: 2026,
    finishedDate: "2026-08-25",
    review: "A darker and more mysterious follow-up to the first book. I enjoyed the suspense around the Chamber of Secrets, the new characters, and how the story expanded the magical world of Hogwarts.",
    tags: ["Fantasy", "Magic", "Mystery"]
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J. K. Rowling",
    isbn: "9781338878943",
    rating: 4.58,
    status: "read",
    genre: "Fantasy",
    year: 2026,
    finishedDate: "",
    review: "One of the strongest books in the series. The mystery surrounding Sirius Black is compelling, and the story adds more depth to Harry's past while introducing some unforgettable characters.",
    tags: ["Fantasy", "Magic", "Mystery"]
  },
  {
    title: "Harry Potter and the Goblet of Fire",
    author: "J. K. Rowling",
    isbn: "9781338878950",
    rating: 4.57,
    status: "read",
    genre: "Fantasy",
    year: 2026,
    finishedDate: "",
    review: "The series becomes much bigger and more intense here. The Triwizard Tournament makes the story exciting, while the ending marks a major turning point for Harry and the wizarding world.",
    tags: ["Fantasy", "Magic", "Adventure"]
  },
  {
    title: "Harry Potter and the Order of the Phoenix",
    author: "J. K. Rowling",
    isbn: "9781338878967",
    rating: 4.5,
    status: "read",
    genre: "Fantasy",
    year: 2026,
    finishedDate: "",
    review: "A longer and more emotional entry in the series. Harry's frustration, the resistance against Umbridge, and the formation of Dumbledore's Army make this feel like a story about growing up and standing up for what matters.",
    tags: ["Fantasy", "Magic", "Resistance"]
  },
  {
    title: "Harry Potter and the Half-Blood Prince",
    author: "J. K. Rowling",
    isbn: "9781338878974",
    rating: 4.58,
    status: "read",
    genre: "Fantasy",
    year: 2026,
    finishedDate: "",
    review: "A fascinating mix of mystery, character development, and darker history. Learning more about Voldemort's past gives the story much more depth, and the ending is one of the most memorable in the series.",
    tags: ["Fantasy", "Magic", "Dark Fantasy"]
  },
  {
    title: "Harry Potter and the Deathly Hallows",
    author: "J. K. Rowling",
    isbn: "9781338878981",
    rating: 4.62,
    status: "read",
    genre: "Fantasy",
    year: 2026,
    finishedDate: "",
    review: "A powerful conclusion to the series. The story brings together years of friendships, sacrifices, mysteries, and conflicts, giving the characters and the wizarding world a satisfying final chapter.",
    tags: ["Fantasy", "Magic", "Adventure"]
  },

  // Tom Gates
  {
    title: "The Brilliant World of Tom Gates",
    author: "Liz Pichon",
    isbn: "9781407120690",
    rating: 4.20,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "Excellent Excuses (and Other Good Stuff)",
    author: "Liz Pichon",
    isbn: "9781407124407",
    rating: 4.39,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "Everything's Amazing (Sort Of)",
    author: "Liz Pichon",
    isbn: "9781407124414",
    rating: 4.43,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "Genius Ideas (Mostly)",
    author: "Liz Pichon",
    isbn: "9781407134505",
    rating: 4.44,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "Tom Gates Is Absolutely Fantastic (at Some Things)",
    author: "Liz Pichon",
    isbn: "9781407134512",
    rating: 4.42,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "Extra Special Treats (Not)",
    author: "Liz Pichon",
    isbn: "9781407134529",
    rating: 4.47,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "A Tiny Bit Lucky",
    author: "Liz Pichon",
    isbn: "9781407148809",
    rating: 4.45,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "Yes! No. (Maybe...)",
    author: "Liz Pichon",
    isbn: "9781407148816",
    rating: 4.42,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "Top of the Class (Nearly)",
    author: "Liz Pichon",
    isbn: "9781407161327",
    rating: 4.44,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "Super Good Skills (Almost)",
    author: "Liz Pichon",
    isbn: "9781407163147",
    rating: 4.41,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School"]
  },
  {
    title: "DogZombies Rule (For Now)",
    author: "Liz Pichon",
    isbn: "9781407171340",
    rating: 4.42,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Adventure"]
  },
  {
    title: "Family, Friends and Furry Creatures",
    author: "Liz Pichon",
    isbn: "9781407178349",
    rating: 4.51,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Family"]
  },
  {
    title: "Epic Adventure (Kind Of)",
    author: "Liz Pichon",
    isbn: "9781407178356",
    rating: 4.47,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Adventure"]
  },
  {
    title: "Biscuits, Bands and Very Big Plans",
    author: "Liz Pichon",
    isbn: "9781407186726",
    rating: 4.45,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Music"]
  },
  {
    title: "What Monster?",
    author: "Liz Pichon",
    isbn: "9781407189314",
    rating: 4.48,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Adventure"]
  },
  {
    title: "Mega Make and Do and Stories Too!",
    author: "Liz Pichon",
    isbn: "9781407143620",
    rating: 4.36,
    status: "read",
    genre: "Activity",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Activities", "Humor"]
  },
  {
    title: "Spectacular School Trip (Really...)",
    author: "Liz Pichon",
    isbn: "9781407193519",
    rating: 4.50,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School", "Adventure"]
  },
  {
    title: "Ten Tremendous Tales",
    author: "Liz Pichon",
    isbn: "9781407193526",
    rating: 4.48,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Stories"]
  },
  {
    title: "Random Acts of Fun",
    author: "Liz Pichon",
    isbn: "9780702307447",
    rating: 4.52,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Fun"]
  },
  {
    title: "Happy to Help (Eventually)",
    author: "Liz Pichon",
    isbn: "9780702315343",
    rating: 4.53,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Family"]
  },
  {
    title: "Five Star Stories",
    author: "Liz Pichon",
    isbn: "9780702325021",
    rating: 4.54,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Stories"]
  },
  {
    title: "Book of Everything!",
    author: "Liz Pichon",
    isbn: "9780702331589",
    rating: 4.46,
    status: "read",
    genre: "Activity",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Activities", "Humor"]
  },
  {
    title: "Tom Gates Is Ha! Ha! Hilarious",
    author: "Liz Pichon",
    isbn: "9780702334801",
    rating: 4.32,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Stories"]
  },
  {
    title: "Pesky Pets and Parties (Hopefully)",
    author: "Liz Pichon",
    isbn: "9780702334818",
    rating: 4.30,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "Pets", "Parties"]
  },
  {
    title: "Tom Gates Is Not Famous (Yet!)",
    author: "Liz Pichon",
    isbn: "9780702337772",
    rating: null,
    status: "read",
    genre: "Humor",
    year: 2026,
    finishedDate: "",
    review: "",
    tags: ["Tom Gates", "Humor", "School", "Drama"]
  }
].map(book => ({
  ...book,
  cover: book.cover || `https://covers.openlibrary.org/b/isbn/${book.isbn}-L.jpg?default=false`
}));
